/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MediaRouteImport } from './routes/media'
import { Route as MediaIndexRouteImport } from './routes/media.index'
import { Route as MediaProviderIdRouteImport } from './routes/media.$providerId'
import { Route as MediaPlayerSceneIdRouteImport } from './routes/media.player.$sceneId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaIndexRoute = MediaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MediaRoute,
} as any)
const MediaProviderIdRoute = MediaProviderIdRouteImport.update({
  id: '/$providerId',
  path: '/$providerId',
  getParentRoute: () => MediaRoute,
} as any)
const MediaPlayerSceneIdRoute = MediaPlayerSceneIdRouteImport.update({
  id: '/player/$sceneId',
  path: '/player/$sceneId',
  getParentRoute: () => MediaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/media': typeof MediaRouteWithChildren
  '/media/$providerId': typeof MediaProviderIdRoute
  '/media/': typeof MediaIndexRoute
  '/media/player/$sceneId': typeof MediaPlayerSceneIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/media/$providerId': typeof MediaProviderIdRoute
  '/media': typeof MediaIndexRoute
  '/media/player/$sceneId': typeof MediaPlayerSceneIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/media': typeof MediaRouteWithChildren
  '/media/$providerId': typeof MediaProviderIdRoute
  '/media/': typeof MediaIndexRoute
  '/media/player/$sceneId': typeof MediaPlayerSceneIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/media' | '/media/$providerId' | '/media/' | '/media/player/$sceneId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/media/$providerId' | '/media' | '/media/player/$sceneId'
  id:
    | '__root__'
    | '/'
    | '/media'
    | '/media/$providerId'
    | '/media/'
    | '/media/player/$sceneId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MediaRoute: typeof MediaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/': {
      id: '/media/'
      path: '/'
      fullPath: '/media/'
      preLoaderRoute: typeof MediaIndexRouteImport
      parentRoute: typeof MediaRoute
    }
    '/media/$providerId': {
      id: '/media/$providerId'
      path: '/$providerId'
      fullPath: '/media/$providerId'
      preLoaderRoute: typeof MediaProviderIdRouteImport
      parentRoute: typeof MediaRoute
    }
    '/media/player/$sceneId': {
      id: '/media/player/$sceneId'
      path: '/player/$sceneId'
      fullPath: '/media/player/$sceneId'
      preLoaderRoute: typeof MediaPlayerSceneIdRouteImport
      parentRoute: typeof MediaRoute
    }
  }
}

interface MediaRouteChildren {
  MediaProviderIdRoute: typeof MediaProviderIdRoute
  MediaIndexRoute: typeof MediaIndexRoute
  MediaPlayerSceneIdRoute: typeof MediaPlayerSceneIdRoute
}

const MediaRouteChildren: MediaRouteChildren = {
  MediaProviderIdRoute: MediaProviderIdRoute,
  MediaIndexRoute: MediaIndexRoute,
  MediaPlayerSceneIdRoute: MediaPlayerSceneIdRoute,
}

const MediaRouteWithChildren = MediaRoute._addFileChildren(MediaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MediaRoute: MediaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
